setwd("C:\\Users\\lenovo\\Desktop")
rt=read.table("1input.txt",sep="\t",header=T,row.names=1,check.names=F)
rt=rt[1:nrow(rt),] 
library(pheatmap)
colgroup=read.table("group.txt",sep="\t",header=F,row.names=1,check.names=F,quote="")
View(colgroup)
colnames(colgroup)=c("fustat","gender","age","grade","meta status","Risk")
View(colgroup)
tiff(file="map64665.tiff",width = 30,height = 25,units ="cm",compression="lzw",bg="white",res=500)
pheatmap(rt, annotation_col = colgroup,color = colorRampPalette(c("green", "white", "red"))(50), scale = "row",cluster_row = FALSE,cluster_cols = FALSE,fontsize_row=8,fontsize_col=10)
dev.off()
